// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wuwzwgqezhwftuneslzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1d3p3Z3Flemh3ZnR1bmVzbHp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTM2NDcsImV4cCI6MjA3MDQ4OTY0N30.6St-ezDPfz4UDRZRA4r19YaJcqsfL_gBAomBu2Tpk8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);